### ISSUE TITLE
Integrate "Koha"

### ISSUE THREAD

**Issue by raphaelm** [opacapp/opacclient#101]
Open Source library system, see koha-community.org

**Comment by tuxayo** [comment]
To someone  wanting to try, see https://github.com/opacapp/opacclient/issues/447#issuecomment-240860890

- Try to build the `tmp-sru` branch as said in the comment
- Experiment with the public catalog of Aix-Marseille Université. Here is an example of a query on the API:
http://catalogue.univ-amu.fr:9998/biblios?version=1.1&operation=searchRetrieve&query=test&startRecord=1&maximumRecords=10&recordSchema=mods

**Comment by raphaelm** [comment]
For the record, you don't need the old (and now deleted) ``tmp-sru`` branch, as there is a ``SRU`` implementation in ``master``.

**Comment by johan12345** [comment]
**Status update**: As Koha is becoming more popular in Germany (through [LMSCloud](https://www.lmscloud.de/), who offer Koha hosting), we are now starting to work on implementing full support for Koha OPACs, including account features. As the new Koha API will probably still use SRU for catalogue search, it will only work for Koha libraries that have SRU enabled.
