### ISSUE TITLE
Löschen einer Vormerkung

### ISSUE THREAD

**Issue by hurzl** [opacapp/opacclient#308]
Beim ersten Klick auf das Kreuz passiert gar nichts, es wird nur neu geladen.
Dann muss man nochmal klicken, um die Abfrage "Wirklich löschen?" zu bekommen.

**Comment by johan12345** [comment]
Das ist prinzipiell so gedacht, denn die Kontodaten müssen zuerst neu geladen werden, damit die App nicht versehentlich die falsche Vormerkung löscht (bei manchen Bibliothekssystemen geht das nicht auf der Basis von eindeutigen IDs, sondern anhand der Reihenfolge in der Kontoansicht -> siehe auch #79 ). 

An der Stelle wird aber auch ein [Toast angezeigt](https://github.com/opacapp/opacclient/blob/9872e4c8adf26d24083343eb5f66463cbf0fb53e/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java#L573), der darauf hinweist.
