### ISSUE TITLE
Leere Liste bei Bibliotheksauswahl

### ISSUE THREAD

**Issue by hurzl** [opacapp/opacclient#316]
Bin ich der Einzige, bei dem die Liste leer ist?

**Comment by raphaelm** [comment]
Ja, zumindest hat sich bisher sonst keiner gemeldet  ;) 
Aktuelle Version aus dem Play Store? Wird erst ein "Liste wird geladen" angezeigt oder passiert einfach garnichts?

**Comment by hurzl** [comment]
Aktuelles master, es passiert garnichts.

**Comment by hurzl** [comment]
Jetzt geht es wieder, aber nach Aufruf dauert es ein paar Sekunden, bevor die Liste erscheint.
Kann es damit zu tun haben, dass der Abruf der bestehenden Kontos hängt?

**Comment by raphaelm** [comment]
Nein, mit den bestehenden Kontos hat es nichts zu tun.
Dass es ein paar Sekunden dauert, ist normal, viele Geräte sind zu langsam um die komplette Liste direkt zu laden, dann sollte allerdings auch ein Ladesymbol erscheinen.

**Comment by hurzl** [comment]
Das Ladesymbol kam erst gar nicht, jetzt hat es ca. 3-4 Sekunden gedauert

**Comment by hurzl** [comment]
Jetzt bekomme ich auch Suchergebnisse. Wenn ich von dort "zurück" drücke, ändert sich nur der Titel in "Bibliotheksauswahl", aber die Liste der Suchergebnisse bleibt stehen

**Comment by uvok** [comment]
Worked with the 4.x.x versions for me. 
But in version 5.0.3 from FDroid the list of libraries shown in the setup wizard is empty. Searching and locating doesn't yield any results either.

**Comment by johan12345** [comment]
For the 5.0.3 version from F-Droid, this is not the same bug as above. The F-Droid build server for some reason does not download the library configuration files when building the app and the app is not prepared to update them if there are none included in the app. We will try to fix at least one of these problems this next week.

Until then, please use the Play Store version or the APK available at https://de.opacapp.net/apk/
