### ISSUE TITLE
Bug: Barcode nicht in Suche Formular

### ISSUE THREAD

**Issue by hans207** [opacapp/opacclient#382]
hallo,

beim scannen von Barcodes wird der Scan nicht ins entsprechende Feld eingefügt.

WebOpac 4.4.4
Barcode Scanner 4.7.3
(beides über Fdroid)
ULB Darmstadt Katalogsuche
Android 4.2.2

**Comment by johan12345** [comment]
Bei mir funktioniert es mit der selben Bibliothek
Web Opac 4.4.4, Barcode Scanner 4.7.5 (Play Store), Android 6.0

Ich halte es für unwahrscheinlich, dass es an der neueren Version des Barcode-Scanners liegt, aber vielleicht lohnt es sich trotzdem, mal die neue Version aus dem Play Store oder die APK von https://github.com/zxing/zxing/releases herunterzuladen und zu testen.

Zeigt die Opac-App sofort oder beim nächsten Neustart eine Benachrichtigung zum Senden eines Fehlerberichts an? Bringt es etwas, in den Einstellungen auf "Cache leeren" zu tippen?

**Comment by raphaelm** [comment]
Nein, das hat sicher nichts mit zxing zu tun, eher irgendwelche weirden Dinge die beim App-Wechsel wieder verloren gehen. Wir hatten es z.B. öfter dass durch das drehen des Handys beim Barcode-Scannen direkt nach dem Eintragen des Barcodes ein "Handy gedreht" Event ausgelöst wurde und der Barcode dabei verloren ging o.ä.. Immer relativ schwer zu finden und wenns bei dir nichtmal auftritt...

**Comment by johan12345** [comment]
Auch mit unterschiedlichen Kombinationen der Drehung vor und nach dem Scannen funktioniert es bei mir gut. Und an der älteren Android-Version sollte es eigentlich auch nicht liegen...

**Comment by hans207** [comment]
das Drehen scheint das Problem zu sein,
vor, nach und während scannen nur hochkant halte funktioniert, 
wenn ich Auto-Drehung ausschalte funktionierts auch.

dann schonmal danke

**Comment by johan12345** [comment]
Okay, dann müssen wir das wohl nochmal testen. @raphaelm Hast du ein Gerät, auf dem du es reproduzieren kannst?
