### ISSUE TITLE
Fix wrong english words

### ISSUE THREAD

**Issue by raphaelm** [opacapp/opacclient#397]
- `DetailledItem` → `DetailedItem` (problematic, because it is part of the public API)

**Comment by kingballer29** [comment]
Hello I was wondering if I could try this, and as to what files in particular I should be looking at?

**Comment by raphaelm** [comment]
It's actually the names a file and class… Just do a "Search in directory" and look out for it. And I'm sure there are more wrong things in there ;)

**Comment by rockydcoder** [comment]
@raphaelm please review
