### ISSUE TITLE
Symbole für Verlängerung vertauscht

### ISSUE THREAD

**Issue by lewumpy** [opacapp/opacclient#406]
In der Liste mit den ausgeliehenen Medien erscheint hinter den Medien auf der rechten Seite ein runder Pfeil, mit dem man jedes Medium einzeln verlängern kann.

Seit dem letzten Update ist es nun so, dass bei Medien, die nicht mehr verlängert werden können, der Pfeil dunkelgrau/anthrazit (also in Schriftfarbe) dargestellt wird und bei Medien, die noch verlängert werden können, hellgrau. Vor dem Update hieß hellgrau, das Bücher nicht mehr verlängert werden können. Das war für mich auch intuitiver als jetzt.

Version: 4.5.3
Bibliothek: Stadtbibliothek Halle (Saale)

**Comment by johan12345** [comment]
Eigentlich hat sich an dem Code, der die Farben erzeugt, in den letzten Updates nichts geändert. Daher vermute ich das Problem eher in der Kommunikation der App mit der Bibliothek als mit der eigentlichen Anzeige. Sie könnten uns bei der Fehlersuche
wie folgt behilflich sein: Öffnen Sie die Kontoansicht auf der Website der Bibliothek mit
Ihrem Computer und drücken Sie "Strg+S". Die so abgespeicherte HTML-Datei schicken Sie uns
bitte entweder hier als Anhang oder per E-Mail an info@opacapp.de. Persönliche Informationen wie Ausweisnummer o.ä. können Sie vorher z.B. mit einem Texteditor entfernen.

**Comment by lewumpy** [comment]
Noch als Anmerkung, welche ich oben nicht erwähnt habe: beide Symbole können angewählt werden, nur dass bei dem dunkelgrauen die Meldung kommt, dass die Medien nicht mehr verlängert werden können und bei dem hellgrauen ohne Probleme die Verlängerung durchgeführt werden kann.

Hier die abgespeicherte Seite:
[Benutzerkonto.zip](https://github.com/opacapp/opacclient/files/242239/Benutzerkonto.zip)
