### ISSUE TITLE
Add option to skip 

### ISSUE THREAD

**Issue by raphaelm** [opacapp/opacclient#414]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at *any* point, please do not hesitate and ask us, either here on GitHub or via email at info@opacapp.de. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Open Source or Android development in general and have never done it before. We'd like to ask people with wide experience in contributing to leave this issue to beginners. Thanks!

## How to get started

First of all, we recommend that you [install the app](https://play.google.com/store/apps/details?id=de.geeksfactory.opacclient) and play around with it so you know how it looks and feels. Next, you should use git to download this GitHub repository and open the folder ``opacclient/`` in Android Studio. Press the green "Play" button to run it on your device. If this works, you have a working development setup, yay! If it doesn't, feel free to ask us for help!

If you don't have an account in one of the [supported libraries](https://en.opacapp.net/libraries/), you can select the library that just has the name "Test". Note that this library is only included in the list if you compile the app yourself, you will not find it in the builds from the Play Store.

## What this is about

When you try to renew a lent item (clicking the "refresh" symbol next to an entry in the account view), you will be asked whether you really want to do this, because in some libraries this might cost money etc. Some of our users get annoyed by this, so we want to provide a "Do not ask me again" option to them.

Luckily for you, we already have this feature somewhere else in the app (when trying to reserve an item) and you can take lots of inspiration from there.

## How to do this

I recommend forking this repository and creating a special git branch for this issue before you start. This will make it easier for you to submit a pull request later. If you've never done this before, there are a lot of good guides out there and you can always ask us questions.

* Have a look at ``reservationDo()`` in [SearchResultDetailFragment.java](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java#L879). As you can see there, if the ``reservation_fee_warning_ignore`` setting is set, ``reservationPerform`` will be executed immediately, otherwise the user will be asked to confirm using a dialog built from the [dialog_reservation_fees.xml](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/res/layout/dialog_reservation_fees.xml) layout. If the dialog is confirmed positively and the checkbox "do not ask again" was checked, 
* Create a similar dialog layout ``dialog_prolong_confirm.xml`` (or a similar name)
* Go to ``prolong()`` in [AccountFragment.java](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java#L525) and restructure it in a similar way. You probably want to split it into two functions as well, e.g. ``prolong()`` and ``prolongPerform()``. Decide on a new name for a setting used to store the "do not ask again" state. You do not need to copy over the ``getSupportFlags``-related condition from the ``if``-Statement ``reservationDo``.

We're excited to see your pull request! 

If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://github.com/opacapp/opacclient/blob/master/CODE_OF_CONDUCT.md) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by kgodara** [comment]
Hello, I would love to work on this and am planning to start soon. Unfortunately I am currently having some problems cloning the project from git, but as soon as those are resolved I will work on this,

**Comment by raphaelm** [comment]
Hey @kgodara, I'm afraid but it seems @AdamLazarus is already working on this. We currently do not have another 'easy' ticket open but hopefully we'll have one soon ;)

Let me know if you need help getting that git to do what it should :)

**Comment by raphaelm** [comment]
Fixed in #419

**Comment by johan12345** [comment]
Hi @kgodara, we now have a new 'easy' issue in #426. So if you are interested in working on that, here you go :)

**Comment by johan12345** [comment]
@kgodara Alternatively, we now also have #428.
