### ISSUE TITLE
Add Polish lang

### ISSUE THREAD

**Issue by thesebas** [opacapp/opacclient#418]
Already requested for Polish on https://www.transifex.com/ramidotio/opacapp/

**Comment by raphaelm** [comment]
Hey :) We'll accept the request on transifex as soon as @johan12345 or I get around to update the source files there, today or tomorrow :)

**Comment by johan12345** [comment]
I updated the source files now, I just can't add you as a collaborator because I am not a "Team manager" on Transifex. This needs to be done by @raphaelm.

**Comment by raphaelm** [comment]
As always, I hated transifex for a few minutes for not providing a "accept request" button somewhere I can find it and then added you manually. Should work now :)

**Comment by thesebas** [comment]
(whew) all but 3 labels are translated, now waiting for review ;)

**Comment by raphaelm** [comment]
I added the plural you requested. As we don't have some other Polish developer for review yet, I'll include it without review ;)

**Comment by raphaelm** [comment]
I included the transifex data for the next release. However, I needed to do the following adjustments… https://github.com/opacapp/opacclient/commit/897ab6109218d91f09da0dda38adbae28633eb12
