### ISSUE TITLE
Hannover_Uni.json: new URL

### ISSUE THREAD

**Issue by Tratoschek** [opacapp/opacclient#451]
The TIB/UB has changed their catalogue URL. I'm not sure if other things has changed, too.

The new URL is at:
https://www.tib.eu
and I think, the new baseurl at:
https://opac.tib.eu

**Comment by Tratoschek** [comment]
Thank you for fixing the opac urls. One question, though: I think, the information URL in opacclient/opacapp/src/main/assets/bibs/Hannover_Uni.json should be https://tib.eu (the old URL works, but is a redirection to tib.eu).

**Comment by johan12345** [comment]
Indeed. I fixed that in 858aabd.
