### ISSUE TITLE
Issues building/updating the app

### ISSUE THREAD

**Issue by hurzl** [opacapp/opacclient#453]
1. library/account is gone after I updated app.
2. library list is empty, LeakCanary problems like 
http://stackoverflow.com/questions/31351236/stuck-at-dumping-memory-app-will-freeze-brrr-message

(android 6.0.1)

**Comment by johan12345** [comment]
> library list is empty

please see
https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/LIBRARY_DATA.md

Short version: you need to do `gradlew downloadJson` or `gradlew assembleRelease` to download the library configuration files

**Comment by johan12345** [comment]
> LeakCanary problems like http://stackoverflow.com/questions/31351236/stuck-at-dumping-memory-app-will-freeze-brrr-message

Is the app really freezing like described in the link? For me there's just a notification sometimes that I need to grant the storage permission to Leak Canary (and sometimes that it found a leak, which is something we should look into).

**Comment by johan12345** [comment]
> library/account is gone after I updated app.

Related to

> library list is empty

**Comment by hurzl** [comment]
After I built in release mode I got the list. After I selected a library, no more Leak. But my account is gone.

**Comment by johan12345** [comment]
Well, your account is saved in the app's data. If you removed it during the update (e.g. by uninstalling and reinstalling or by changing the package name -- the debug version uses a different one than the release version), it is gone.

Leak Canary is of course disabled in the release build, so it won't listen for leaks there.

**Comment by hurzl** [comment]
I have the debug version installed.

**Comment by johan12345** [comment]
We will definitely have to look at those leaks, but we have not heard of them affecting the use of the app (as an end user in the release version).

If you have deleted the app data at some time during the update process, your account won't magically reappear by installing it again. So you need to set it up again.

If you install and update the app through the Play Store (or F-Droid if you want) the data will be saved.
