### ISSUE TITLE
libopac dependencies ignored in Android

### ISSUE THREAD

**Issue by sw-dev1** [opacapp/opacclient#462]
Gradle messages:
WARNING: Dependency org.apache.httpcomponents:httpclient:4.3.6 is ignored for debug as it may be conflicting with the internal version provided by Android.
WARNING: Dependency org.json:json:20090211 is ignored for debug as it may be conflicting with the internal version provided by Android.

libopac version 5.05, Android Studio 2.2.2, target 25

Tried ignoring the modules in gradle; warning is gone but the dependent classes e.g. HttpClientBuilder are not recognized. 
Tried useLibrary 'org.apache.http.legacy'; some classes are now recognised, but not all.

**Comment by johan12345** [comment]
For using libopac on Android, you probably need the
```
useLibrary 'org.apache.http.legacy'
```
and
```
compile(project(':libopac')) {
        transitive = false
}
compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
compile 'org.apache.httpcomponents:httpmime:4.3.6'
// maybe some others
```
entries in the Gradle file, as we have it in [ours](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/build.gradle). The warnings will still appear, but it should build fine.

In the long term, we are planning to replace the Apache HTTP client by [okhttp](https://github.com/square/okhttp), which will eliminate those problems. But that is a big task as we have to ensure that it works with all the quirky types of HTTP requests/responses some library systems are using and also the peculiarities of single library servers (such as different SSL configurations).

Out of curiosity: What are you planning to do with libopac? :)

**Comment by sw-dev1** [comment]
Thanks for the explanation. I'll try this. 
I want to build an NFC reader that would take the library id from the item tag, match the item from the account data  and display the expiry date. 
In the meantime - as I couldn't get the libopac to work with my app - I added the functionality on top of the opacclient.  It works quite well now, but Android complains about a memory leak. 
While doing this I had to make changes to the Adis class in the library, in particular in order to parse the item id from the title. I made it work for Stadtbibliothek München. If you are interested, we could discuss on another thread?

**Comment by raphaelm** [comment]
> In the meantime - as I couldn't get the libopac to work with my app - I added the functionality on top of the opacclient. 

Even better :)

> It works quite well now, but Android complains about a memory leak.

Yeah, LeakCanary does that from time to time, we haven't found the source yet. It might not even be caused by your code.

> While doing this I had to make changes to the Adis class in the library, in particular in order to parse the item id from the title. I made it work for Stadtbibliothek München. If you are interested, we could discuss on another thread?

Cool! The best way would be for you to propose a pull request that adds these changes to our Adis implementation. I'd love to see that!

If you have trouble with creating the pull request, I'm glad to help :)

**Comment by sw-dev1** [comment]
Hm, no progress trying the instructions above. Compile passes, but now getting a runtime exception 

`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClientBuilder; 
.....
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.HttpClientBuilder" on path: DexPathList.....
`
As mentioned above, I need to adapt the libopac, so I am trying to use it as a project module, the same way opacclient does. I have exactly the same build.gradle for the libopac project  and of course
 `compile(project(':libopac')) {
        transitive = false
    }`
in the app module build.gradle.

All this is with a new app created with the latest Android Studio from a Basic Activity template. 

Any chance of help to get this running? 

I received your comment while writing this. I will make a pull request.

**Comment by johan12345** [comment]
Hm, strange 😕. So you also have
```groovy
compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
compile 'org.apache.httpcomponents:httpmime:4.3.6'
```
in the Gradle file of your app in addition to the libopac entry? Those should include the `HttpClientBuilder` class. If you do it the same way as in [our build.gradle](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/build.gradle), it should just work...

**Comment by sw-dev1** [comment]
OK, got it now. This was missing from the app`s build.gradle:
```
packagingOptions {
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
    }
```

**Comment by johan12345** [comment]
Interesting, I forgot about those lines :wink:. The reason is that multiple libraries include these files in the META-INF directory, which causes a conflict when the Android Gradle plugin packages them into the APK. `LICENSE` files seem to be excluded by default, but `NOTICE` files are not.

Thanks for the feedback!

**Comment by sw-dev1** [comment]
Hmm, next problem at runtime: `java.lang.ClassNotFoundException: Didn't find class "org.jsoup.Jsoup"`. I have `compile 'org.jsoup:jsoup:1.8.3'` in the libopac build.gradle.

**Comment by sw-dev1** [comment]
Thanks, that did it.

**Comment by sw-dev1** [comment]
Needed also` joda-time ` but not `'org.apache.httpcomponents:httpmime:4.3.6'`. Probably due to the apache android legacy library?

So the correct way of using libopac would be:
Add the library to the main app, setting transitive to false. Copy all dependencies from libopac's build.gradle to the main app's buld. gradle except
`'org.apache.httpcomponents:httpmime:4.3.6'`
