### ISSUE TITLE
Tübingen, Unibibliothek - Problem Encountered

### ISSUE THREAD

**Issue by github-user-1** [opacapp/opacclient#463]
When checking my account with "Tübingen, Unibibliothek" I'll get the following error message:

![screenshot_2016-12-08-17-51-47](https://cloud.githubusercontent.com/assets/6796538/21019517/a1c552d8-bd68-11e6-817c-3e1ca7ee5b3b.png)

Checking the account via the webinterface is working perfectly fine.

**Comment by johan12345** [comment]
Does this problem occur all the time or just sometimes?

If it occurs always, it seems that this library uses a different layout to display the list of reservations in the web interface. Could you send us (either here or via e-mail info@opacapp.de) the HTML source code of the web page where the reservation list is displayed?

**Comment by raphaelm** [comment]
I will release a new version of the app tonight that *MIGHT* fix the issue. I'm waiting for your feedback then :)

**Comment by johan12345** [comment]
Closing because we received no feedback.
