### ISSUE TITLE
Requirement: Sorting in catalog search result [v5.0.6]

### ISSUE THREAD

**Issue by akramer-zibra** [opacapp/opacclient#472]
Would be great to have a feature which enables sorting in catalog search result view like in original OPAC:
"Jahr abwärts", "Jahr aufwärts", "Verfasser" and "Titel".

**Comment by johan12345** [comment]
We already support this for some OPAC systems. Which library are you using?

**Comment by johan12345** [comment]
Closing because we did not receive an answer.
