### ISSUE TITLE
Account editing view: Add visibility toggle to password input

### ISSUE THREAD

**Issue by johan12345** [opacapp/opacclient#473]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at info@opacapp.de. We'll be very happy to help!

We think this issue is very suitable to people who are just starting with Open Source or Android development in general and have never done it before. We'd like to ask people with wide experience in contributing to leave this issue to beginners. Thanks!

## How to get started

First of all, we recommend that you [install the app](https://play.google.com/store/apps/details?id=de.geeksfactory.opacclient) and play around with it so you know how it looks and feels. Next, you should use git to download this GitHub repository and open the folder `opacclient/` from within the repository (not the repository itself) in Android Studio.

Because of a [Bug in Android Studio](https://code.google.com/p/android/issues/detail?id=172347), some configuration files in the `.idea` folder might be deleted after opening the project for the first time. Run `git checkout -- opacclient/.idea/` in the repository to revert this.

Before running the app, you should run the `downloadJson` Gradle task which loads the configuration files for all the libraries in the app from our server. You can either do this using Android Studio's *Gradle Tool Window* or by running `gradlew downloadJson` on the command line.

Press the green "Play" button to run it on your device. If this works, you have a working development setup, yay! If it doesn't, feel free to ask us for help!

## What this is about

When you start the app and set up a library account, you can input details of your account, namely a label, your username or library membership ID and password. This issue is about the password input field.

The Android Support Library supports adding a button to password input fields that allows you to toggle the password between the normal "disguised" state and a visible state. An example of this can be seen [here](https://material.io/guidelines/components/text-fields.html#text-fields-password-input).

We would like you to add this button to our password input. As a security measure, it should only be shown when an account is first created or when there is no password currently set for the account. This makes sure that the password can not be revealed later by a malicious user opening the account editing view again.

## How to do this

We recommend forking this repository and creating a special git branch for this issue before you start. This will make it easier for you to submit a pull request later. If you've never done this before, there are a lot of good guides out there and you can always ask us questions.

The Java source file you need to look at is [`AccountEditActivity.java`](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountEditActivity.java). In the `onCreate` method, the password field (`etPassword`) is filled with the password if one was already set.

You should add some code to the end of the `onCreate` method which
- checks if the contents of the password field are empty (which means the account is new or there was no password set before)
- if so, enables the password visibility toggle for the `TextInputLayout` called `tilPassword`.

You can find the documentation how to enable the toggle [here](https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html#setPasswordVisibilityToggleEnabled(boolean)).

We're excited to see your pull request!

If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://github.com/opacapp/opacclient/blob/master/CODE_OF_CONDUCT.md) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by raphaelm** [comment]
Yes, very good idea!

**Comment by ihorie** [comment]
@johan12345 ,
I tried to work on this issue and an error occured when I was setting dev environment.
The error message is like:
  Unresolved dependencies
     Failed to resolve: com.github.johan12345:material-intro:custome_layout-SNAPSHOT

It seems I missed some dependencies but I'm not sure where I can download it.
Could you please help me to solve this issue?

I use:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
and 
Android 2.2.3

**Comment by johan12345** [comment]
The dependency you mentioned should be loaded from [JitPack](https://jitpack.io/). Could it be some kind of connection error? Maybe it shows more information about the error if you run `./gradlew assembleDebug --info`.

**Comment by johan12345** [comment]
Another problem (that however can't explain the dependency error): Our app does not support Android 2.2, the minimum is 2.3 (API level 9).

**Comment by johan12345** [comment]
I'm now also seeing the same error. I'll try to find out what the problem is.

**Comment by johan12345** [comment]
The error should be fixed with https://github.com/opacapp/opacclient/commit/07c969508e0329da788f3620b2899cac31a2df3a.
