### ISSUE TITLE
Add copy data to "share" output

### ISSUE THREAD

**Issue by raphaelm** [opacapp/opacclient#474]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at info@opacapp.de. We'll be very happy to help!

We think this issue is very suitable to people who are just starting with Open Source or Android development in general and have never done it before. We'd like to ask people with wide experience in contributing to leave this issue to beginners. Thanks!

## How to get started

First of all, we recommend that you [install the app](https://play.google.com/store/apps/details?id=de.geeksfactory.opacclient) and play around with it so you know how it looks and feels. Next, you should use git to download this GitHub repository and open the folder `opacclient/` from within the repository (not the repository itself) in Android Studio.

Because of a [Bug in Android Studio](https://code.google.com/p/android/issues/detail?id=172347), some configuration files in the `.idea` folder might be deleted after opening the project for the first time. Run `git checkout -- opacclient/.idea/` in the repository to revert this.

Before running the app, you should run the `downloadJson` Gradle task which loads the configuration files for all the libraries in the app from our server. You can either do this using Android Studio's *Gradle Tool Window* or by running `gradlew downloadJson` on the command line.

Press the green "Play" button to run it on your device. If this works, you have a working development setup, yay! If it doesn't, feel free to ask us for help!

## What this is about

When you start the app and set up a library account (just choose any library and select "anonymous account", you do not need a password), you can search for items in that library. If you click one of the results, you get into the detail view. Here, (either as an icon in the top-right area or in the menu) there is a share button that allows you to "Export details".

This will allow you to send the media information (author, title, year, ...) to another app. If you scroll down in the detail view, you see that in most libraries we also have information on the specific copies of that item, e.g. how many there are, where, if they are available, etc. It would be nice to include them in the exported output as well.

## How to do this

We recommend forking this repository and creating a special git branch for this issue before you start. This will make it easier for you to submit a pull request later. If you've never done this before, there are a lot of good guides out there and you can always ask us questions.

The Java source file you need to look at is [`SearchResultDetailFragment.java`](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java). In the `onOptionsItemSelected` method around line 670, there is a part that constructs a string `text` that can be sent to other apps via the "share" option in the app if a search result is opened.

You should add some code there which
- reads all ``Copy`` elements from ``getItem().getCopies()``
- adds appropriate blocks to `text`

You can have a look at the ``onBindViewHolder`` method in ``CopiesAdapter.java`` or at ``Copy.java`` itself to see which fields are available.

We're excited to see your pull request!

If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://github.com/opacapp/opacclient/blob/master/CODE_OF_CONDUCT.md) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by geomcmaster** [comment]
I'll give this a shot!
