### ISSUE TITLE
Version 5.1.4 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [opacapp/opacclient#483]
Dear team,

when I take a look in the play store I see the version mentioned above. 
When I look to F-Droid the current version is 5.1.3.

What is the reason for this? Is there a failure in the build process?

Kind Regards,
Krawei

**Comment by raphaelm** [comment]
I have no idea, you'd need to ask f-droid. But apparently, the version has been build just 10 minutes ago: https://f-droid.org/wiki/page/de.geeksfactory.opacclient/lastbuild_174 Maybe it takes some time until its in the store?

**Comment by johan12345** [comment]
It seems to always take the F-Droid server a few days to recognize a new version and then build it. The new version was just detected 17 hours ago:
https://gitlab.com/fdroid/fdroiddata/commit/206a78a2d03916a13338a865b56b962b10c7fbf2
see also:
https://f-droid.org/wiki/page/FAQ_-_App_Developers#I.27ve_published_a_new_release._Why_is_it_not_in_the_repository.3F
