### ISSUE TITLE
Export and import favorites list

### ISSUE THREAD

**Issue by johan12345** [opacapp/opacclient#484]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at info@opacapp.de. We'll be very happy to help!

We think this issue is very suitable to people who are just starting with Open Source or Android development in general and have never done it before. We'd like to ask people with wide experience in contributing to leave this issue to beginners. Thanks!

## How to get started

First of all, we recommend that you [install the app](https://play.google.com/store/apps/details?id=de.geeksfactory.opacclient) and play around with it so you know how it looks and feels. Next, you should use git to download this GitHub repository and open the folder `opacclient/` from within the repository (not the repository itself) in Android Studio.

Before running the app, you should run the `downloadJson` Gradle task which loads the configuration files for all the libraries in the app from our server. You can either do this using Android Studio's *Gradle Tool Window* or by running `./gradlew downloadJson` on the command line.

Press the green "Play" button to run it on your device. If this works, you have a working development setup, yay! If it doesn't, feel free to ask us for help!

## What this is about

When you start the app and set up a library account (just choose any library and select "anonymous account", you do not need a password), you can search for items in that library. If you click one of the results to go to the detail view, there is a "star" icon to add this item to your favorites list.

The favorites list is only saved locally in the app - so when users switch to a new phone, the items that were saved to their favorites list will be gone (if you don't use any backup solution). This is why we would like you to add a simple export and import functionality to the app.

We already have a feature that allows to share the items on the favorites list as a human-readable text (including the book title and the link to the library catalog), but we think that for an export/import functionality, the better data format would be a JSON file.

## How to do this

We recommend forking this repository and creating a special git branch for this issue before you start. This will make it easier for you to submit a pull request later. If you've never done this before, there are a lot of good guides out there and you can always ask us questions.

The favorites list is displayed by the `StarredFragment` class, which also contains the [implementation of our current sharing feature](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/StarredFragment.java#L228). We would like you to create a similar function that exports the data to a JSON file and allows the user to choose a location to save it to. You can add a menu item to the Action Bar that will trigger this export feature.

You can create the JSON data either manually using the [JSONObject](https://developer.android.com/reference/org/json/JSONObject.html) and [JSONArray](https://developer.android.com/reference/org/json/JSONArray.html) classes included in Android or automatically using the [Moshi](https://github.com/square/moshi) library, which we already use in the app for other purposes. The JSON file should include:

- The ID of the library which this list is for (-> a list of favorites cannot be transferred to a different library), which can be obtained using `app.getLibrary().getIdent()`
- The list of items on the list, which their three properties `mNr` (media ID in the library catalog), `title` and `mediaType`. (see the [Starred](https://github.com/opacapp/opacclient/blob/master/opacclient/libopac/src/main/java/de/geeksfactory/opacclient/objects/Starred.java) class)

When you are ready with creating the JSON data, you can let the user choose where to save it. We think the best way for this is using Android's [Storage access framework](https://developer.android.com/guide/topics/providers/document-provider.html#create), because it does not require additional permissions and already provides you with a file chooser dialog. However, it is only available on Android 4.4 and above, so you need to make sure that the app displays an appropriate message (or allows to save the data using a "share" intent instead) on older versions.

The last part would be to add an additional menu item to the Action Bar for the import feature. This should then again display a file chooser, load the JSON data, check if the list is for the same library and then save the items to the favorites list.

We're excited to see your pull request!

If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://github.com/opacapp/opacclient/blob/master/CODE_OF_CONDUCT.md) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by kedarmp** [comment]
Hey Johan, I have begun working on this. However, in `StarredFragment`, shouldn't the current menu item "Export" be actually called "Share"? Especially since we are explicitly adding an export feature, it would make sense to rename the existing menu item.

**Comment by johan12345** [comment]
Hi Kedar, 
great! Yes, renaming the items makes sense. You can use the current "export" string for the new export feature and change the other one to "share".
Let us know if you have more questions!
Cheers, 
Johan

**Comment by kedarmp** [comment]
Hey Johan, 
I am done with the part where I can import/export favorites as per specification(Android 4.4 and above only as of now). However I have two questions:

1. Just to be clear, for Android versions <4.4, is creating the same JSON file and then showing a Share action with that file acceptable?
2. Currently, I write the starred list to a temporary file(internal storage). After the user decides the location/file name, that file is copied over into the correct destination. In case the original file (temporary) cannot be created, the user is notified via a Toast letting him know that the action was unsuccessful. Is that acceptable?

**Comment by raphaelm** [comment]
> Just to be clear, for Android versions <4.4, is creating the same JSON file and then showing a Share action with that file acceptable?

Yep, perfect!

> Currently, I write the starred list to a temporary file(internal storage). After the user decides the location/file name, that file is copied over into the correct destination. In case the original file (temporary) cannot be created, the user is notified via a Toast letting him know that the action was unsuccessful. Is that acceptable?

Do you really need the temporary file? Could you also just hold the contents in a string/JSONObject in memory or even only start generating them after the location has been chosen? I think that would be the easier solution as it is pretty failsafe and does not require us to clean up temporary files.

If you need the temporary file, I think a Toast is a reasonable notification for the error case, since the only reason I could imagine for a temporary file not being created is the disk being full and from my own experience, if your disk is full, you have a couple of other problems with your device… However as I said, we should take great care to clean up the temporary files afterwards.

**Comment by kedarmp** [comment]
So, I've completed the Share action for Android versions <4.4. Also I've removed the need for using a temporary file for exporting to storage. I don't know why I needed that in the first place. 
However, on Android (<4.4), I have used the external cache directory to export the file. That I believe is unavoidable.  I shall create a pull request soon.

Also, the current implementation allows the "Share" action to proceed even if the starred list is empty. How should the behavior (now) be? If a Toast/Snackbar showing that the list is empty is alright, do you want me to create a new issue for the same? Thanks!

**Comment by Kartik2016** [comment]
I am a begginer. Please let me know if the issue is still open and can i work on it?

**Comment by johan12345** [comment]
@Kartik2016 Hi, sorry, @kedarmp is already working on this.

Unfortunately, @raphaelm and I currently don't have another "easy" issue in mind.

There is always the possibility to [implement support for a new OPAC system](https://github.com/opacapp/opacclient/wiki/Adding-a-new-library#the-opacapi-interface) (for example one that your local library uses), starting with some improvements to the favorites list (e.g. #471, #28), creating additional Unit Tests (#433) or helping with [translations](https://www.transifex.com/ramidotio/opacapp/) - but all of these are more difficult tasks than the "easy" issues we usually have.

**Comment by johan12345** [comment]
Implemented via #485
