### ISSUE TITLE
Add option to disable loading of covers on mobile data

### ISSUE THREAD

**Issue by johan12345** [opacapp/opacclient#502]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at info@opacapp.de. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Open Source or Android development in general and have never done it before. We'd like to ask people with wide experience in contributing to leave this issue to beginners. Thanks!
## How to get started

First of all, we recommend that you [install the app](https://play.google.com/store/apps/details?id=de.geeksfactory.opacclient) and play around with it so you know how it looks and feels. Next, you should use git to download this GitHub repository and open the folder `opacclient/` in Android Studio. Press the green "Play" button to run it on your device. If this works, you have a working development setup, yay! If it doesn't, feel free to ask us for help!

If you don't have an account in one of the [supported libraries](https://en.opacapp.net/libraries/), you can select the library that just has the name "Test". Note that this library is only included in the list if you compile the app yourself, you will not find it in the builds from the Play Store.
## What this is about

When you search for books in the catalog of a library, in many cases the app will display the cover picture of the book -- in the search result list, in the detail view or even both. A few users have requested that there should be an option in the app to disable downloading these covers while they are on a mobile data network so that the app uses slightly less data.
## How to do this

We recommend forking this repository and creating a special git branch for this issue before you start. This will make it easier for you to submit a pull request later. If you've never done this before, there are a lot of good guides out there and you can always ask us questions.
- Create a new setting (`CheckBoxPreference`) in the [settings.xml](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/res/xml/settings.xml) file and add the corresponding strings in English. We can handle the translations for you. We think the setting best fits in the general category called "Web Opac". The default behavior should be to always load covers (as previously).
- We have recently decided to access all new preferences not directly, but using our [`PreferenceDataSource`](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/storage/PreferenceDataSource.java) class. So you should implement new methods there that access the new preference.
- Have a look at [`ResultsAdapter`, Line 156](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/ResultsAdapter.java#L156). As you can see there, if `item.getCover()`, which holds the cover URL, is set, the cover will be loaded. Here, you need to add an additional check the state of your newly-added setting and then, if needed, check whether the user is on a mobile network (e.g. using [`ConnectivityManagerCompat.isActiveNetworkMetered()`](https://developer.android.com/reference/android/support/v4/net/ConnectivityManagerCompat.html#isActiveNetworkMetered(android.net.ConnectivityManager)). If the cover should not be loaded, we can just show the media type icon as already implemented here.
- The same logic also needs to be implemented in [`SearchResultDetailFragment`, Line 1299](https://github.com/opacapp/opacclient/blob/master/opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java#L1299) so that the `LoadCoverTask` is only executed when the preference is set to always load covers or when the device is on an unmetered network.
- Test your new setting on a device or emulator with a library that supports displaying covers.

We're excited to see your pull request! 

If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://github.com/opacapp/opacclient/blob/master/CODE_OF_CONDUCT.md) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by johan12345** [comment]
Note to self: notify support ticket#2332344 when done

**Comment by vivekscl** [comment]
Hi! I'm new to Android development and would like to work on this! :smile:

**Comment by johan12345** [comment]
Great! Go ahead and let us know when you have any questions.

**Comment by vivekscl** [comment]
So I've been working on this for awhile now but I can't seem to find an `emulator with a library that supports displaying covers`. May I know where I can find this? :sweat_smile: 

For now, the media type icon is loaded regardless.
![deepinscreenshot_select-area_20180210001509](https://user-images.githubusercontent.com/17037188/36037343-78cd53cc-0df7-11e8-95c9-ac00090f8775.png)

**Comment by johan12345** [comment]
Sorry for the ambiguous wording - I meant that the change should be tested with a `device or an emulator` (so either a physical smartphone or the Android emulator on your computer), and with a `library that supports displaying covers`. You seem to have selected a library in the app that does not display covers in their catalog (and thus, in the app).

An example for a library that has covers would be the "Kornhausbibliotheken" in Bern, Switzerland. When you add an account in the app you can either search for "Bern" or select it via "Schweiz -> Bern ->Bern -> Kornhausbibliotheken".

**Comment by vivekscl** [comment]
Oh! I understand it now. Thanks for the clarification! :smile:
