### ISSUE TITLE
SUB Göttingen now seems to support https

### ISSUE THREAD

**Issue by hcmh** [opacapp/opacclient#517]
Hi,
when using the web-interface of the university library of Göttingen (https://opac.sub.uni-goettingen.de), it seems like https-connections using TLS 1.2 are now supported.

Is it now possible to have Web Opac use TLS when connecting to this server? Or is it using a separate API which still doesn't support TLS?

Best wishes,
Christian Holme

**Comment by johan12345** [comment]
Hi,

thanks for the notification!

I have updated the URL in the library data - after updating it using the option in the app's settings or waiting for 1-2 days so that it is updated automatically, the app should now use TLS to connect to the OPAC.
