### ISSUE TITLE
Make status indicator circles accessible for color-blind people

### ISSUE THREAD

**Issue by johan12345** [opacapp/opacclient#523]
In the search result list, the app can show show red, green or yellow circles for items that are available, unavailable or partially available (e.g. only one of the copies), if the library supports it. These circles are difficult to distinguish for people with red-green color blindness.

A possible solution would be to replace these circles with appropriate icons (e.g. a green check mark, a red cross and something else in yellow) from the Material Design Icons pack.

suggested by internal support ticket # 2335350

**Comment by rmereddy** [comment]
Hi,
Is this issue open ? i would like to work on it.

Thanks,
Rohit

**Comment by johan12345** [comment]
Great! Yes, nobody is working on this yet.

You can find some information on how to build the project here:
https://github.com/opacapp/opacclient/wiki/How-to-build-the-project

When you start the app and are prompted to select a library, you can for example try "Deutschland -> Thüringen -> Erfurt -> Stadt- und Regionalbibliothek" (the city library of Erfurt, Germany) and select to use an anonymous account (you don't need login data just for searching in the catalogue). This library should show the red, green or yellow circles for most results in the catalogue search.

Let us know if you need any help!

**Comment by rmereddy** [comment]
thanks  will start working on it and i'm downloading android studios now.

**Comment by rmereddy** [comment]
i have the app running now .Do material icon pack come preinstalled with android studios or do i have to install them from some where?

**Comment by johan12345** [comment]
Material icons are included in Android Studio, see here: https://developer.android.com/studio/write/vector-asset-studio#materialicon

**Comment by foxtrot95** [comment]
Hi, I was also working on this issue. Made a pull request.

**Comment by johan12345** [comment]
Thanks, I will have a look - would have been nice if you would have first asked if @rmereddy is still working on this...
