### ISSUE TITLE
Icon misaligned in landscape mode

### ISSUE THREAD

**Issue by splitt3r** [opacapp/opacclient#525]
As you can see in the screenshot the icon in the sidebar is way to big.

![sidebar](https://user-images.githubusercontent.com/1869584/42415069-f13ccd9a-8243-11e8-9445-e5b9da6317c8.png)

**Comment by foxtrot95** [comment]
Hi, I want to contribute. Is this issue still open?

**Comment by johan12345** [comment]
Yep, this still seems to be an issue. We probably need to specify a different height for the top part of the drawer (`navigation_drawer_header_height`) or reduce the size of the icon in landscape mode (or a combination of both - just see what looks best). Would be great if you could take a look!

**Comment by foxtrot95** [comment]
I fixed it by changing the size of the icon in relation to the space left and by adjusting the height for the top part of the drawer (I increased it a little bit). So no overlapping in landscape mode anylonger.

**Comment by johan12345** [comment]
Sounds good! Can you make a Pull Request?

**Comment by splitt3r** [comment]
#534 fixed it. Looks good now 👍
