### ISSUE TITLE
Stadtbibliothek Achim Not working

### ISSUE THREAD

**Issue by tzelzix** [opacapp/opacclient#526]
Tried multiple Samsung phones. Always get a connection error.

Occurs with and without Account.

When entering account information the app warns that https is not availble

**Comment by johan12345** [comment]
The library changed the URL of their OPAC and also enabled HTTPS for it. We needed to update the URL accordingly in the [configuration files](https://github.com/opacapp/opacapp-config-files/commit/65bb15079d629758e36cd4947ef50d8922ec4210). It should work now, after updating the library data with the corresponding button in the app's settings.
