### ISSUE TITLE
no support anymore for fdroid?

### ISSUE THREAD

**Issue by 0lm** [opacapp/opacclient#536]
hi there
unfortunately its already 10 days ago that wenopac got an update on googleplay/yalpstore. im using the f-droid version but it is still at version 5.4.4. will webopac not be released on fdroid anymore?

**Comment by johan12345** [comment]
Hi, the problem with F-Droid is that we don't have much control over when and how the app gets built by them and then uploaded to the repository. Also, we don't get notified when something goes wrong on their side.

In this case, there were some lint issues in the last release (which we fixed afterwards), which caused the F-Droid build to fail. It should work again for the next release.
