### ISSUE TITLE
Library data outdated: Fachhochschule Bielefeld

### ISSUE THREAD

**Issue by s4b7r** [opacapp/opacclient#538]
Thank you very much for the usefull app!

Lately, the WebOPAC of Bielefeld University of Applied Sciences / Fachhochschule Bielefeld has been updated and moved to a new domain. Could you please check whether the new WebOPAC is still compatible with Web Opac App and update the library data?

As far as I can see, only the _baseurl_ changed from _https://netbz05.fh-bielefeld.de/webOPACClient_ to _https://bib5w.fh-bielefeld.de/webOPACClient_.

**Comment by johan12345** [comment]
Thank you for notifying us! Indeed, only the URL changed. I have updated it in our system, you should now be able to use it again in the app after clicking the "update library data" button in the settings. The update should also soon be reflected in the opacapp-config-files repository.
