### ISSUE TITLE
Cannot access TUM library. 

### ISSUE THREAD

**Issue by ongun-kanat** [opacapp/opacclient#542]
Both authenticated and anonymous access for TUM Unibibliothek is failing with server error. Is it still supported?

**Comment by raphaelm** [comment]
They apparently changed their OPAC system. I changed our configuration now: https://github.com/opacapp/opacapp-config-files/commit/1943675cf5bc494877f164b0e9e8e3d52f879216

I didn't test it, though. You can test it using the "Refresh library configurations" at the bottom of the app's settings screen.

**Comment by ongun-kanat** [comment]
Tested it now it says login failed but no information has been provided in the error message. 
![](https://i.imgur.com/uWPTZ7p.png)
