### ISSUE TITLE
Refresh and renew icons

### ISSUE THREAD

**Issue by StefRe** [opacapp/opacclient#551]
Not a real issue - just a remark or suggestion.
I regularly use the 'renew all items' function. This function is available from the overflow menu, but I'm always tempted to click the refresh icon (and often indeed do it just to learn that it doesn't do what I want it to do), because - at first sight - the `refresh` icon ![baseline_refresh_black_18](https://user-images.githubusercontent.com/19879328/50551341-53ee0b00-0c7f-11e9-8a38-551a56180a76.png) in the toolbar looks pretty similar to the `replay` icons ![baseline_replay_black_18](https://user-images.githubusercontent.com/19879328/50551342-56506500-0c7f-11e9-8ece-0366455feebd.png) used for renewals in the list.
So my question/suggestion is: wouldn't it be clearer to use a more specific icon for the renewal function? Just for illustrative purposes I created two variants out of the existing [material icons](https://material.io/tools/icons/?icon=refresh&style=baseline) using the `calendar_today` icon with some arrows:
![verlangern1](https://user-images.githubusercontent.com/19879328/50551135-c3163000-0c7c-11e9-8603-c9ef2abb6276.png) ![verlangern2](https://user-images.githubusercontent.com/19879328/50551137-c6112080-0c7c-11e9-802f-720474476354.png)
What do you think about it? Again, this is not a big deal, just a minor comment trying to make the app more intuitive to use.

**Comment by johan12345** [comment]
Yeah, it's a good Idea to make the two icons more distinct. However, in this case, we do need to consider that changing the icon will also confuse existing users...

Another idea how to deal with this situation: We could also hide the refresh icon from the toolbar and move it to the overflow menu (as we also have pull-to-refresh implemented on that screen).

@raphaelm , what's your opinion on this?

**Comment by raphaelm** [comment]
I think existing users would get it, and I somehow like the second proposal, although I'm not sure it's simple enough to look clean on small screens.

> Another idea how to deal with this situation: We could also hide the refresh icon from the toolbar and move it to the overflow menu (as we also have pull-to-refresh implemented on that screen).

Agreed, that would be a decent option.

**Comment by StefRe** [comment]
> Another idea how to deal with this situation: We could also hide the refresh icon from the toolbar and move it to the overflow menu (as we also have pull-to-refresh implemented on that screen).

I'm fine with that too.

**Comment by johan12345** [comment]
I have now moved the "refresh" button to the overflow menu and added a hint for users who might be unaware of pull-to-refresh. The change will be included in the next release.
