### ISSUE TITLE
Munich: Reserving a book is not working

### ISSUE THREAD

**Issue by c64bob** [opacapp/opacclient#560]
I'm trying to reserve a book in Munich's library (Münchner Stadtbibliothek). I get asked details about which location I want to pick it up, whether I want an email notification, and a confirmation that costs will result. However, after finishing this process, the reserved book is not visible in my account, neither mobile nor on the website. There is no error message.

How can I troubleshoot the problem, e.g. is there a log file somewhere?

**Comment by johan12345** [comment]
Hi,

We already had some problems before with reservations in Munich a few years ago (https://github.com/opacapp/opacclient/search?q=munich+reservations&unscoped_q=munich+reservations&type=Commits), maybe they changed something in their reservation process again.

There is not really a log file (it would need to save the HTML contents of the web pages the app is accessing in the background, which could take up a lot of space, would be difficult to view on a smartphone, and could potentially be a privacy risk). But you could for example try to use Android Studio to debug the app and e.g. set a breakpoint at the end of the `htmlPost` function of `Adis.java` to look at the HTML and see at which point it goes wrong.

**Comment by c64bob** [comment]
Thanks for the pointer, that's helpful.

I see [here](https://github.com/opacapp/opacclient/blob/3e3d9a68f3820d31ae6f9a6be93a2795d2bd9de1/opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java#L816) that to submit the reservation, we are looking for a text button with a value of "Reservation abschicken". However, in the Munich library the button's value is "Bestellung abschicken".

I'll try and build a modified version and test if reservation works with this modification.

**Comment by johan12345** [comment]
We have had a PR that addressed reservations in Munich (#610), which will be included in the next app update.
If there are still problems after that, please reopen the issue.
