### ISSUE TITLE
Changed OPAC Software "Büchereien Wien"

### ISSUE THREAD

**Issue by berndy2001** [opacapp/opacclient#565]
After a [hacker attack](https://www.wien.gv.at/info/datenschutz/verletzung-buechereien.html), the Vienna Library (Büchereien Wien) has a [new OPAC software](https://www.buechereien.wien.at/Konto). They have also changed the password from Date of Birth to a new specific password. A connection to the customer account is currently not possible with the Web Opac App.

**Comment by johan12345** [comment]
We are aware of this. The new OPAC is OCLC OPEN, which we already support. But an [adjustment](https://github.com/opacapp/opacclient/commit/f2e950fa20b6cbd502cb7ee8fd2dfde50d5a5ae4) was necessary to make it work in Vienna and it will be included in the next update of the app.

However, for now, only catalog search will work in the open source app. Account features for OPEN are only supported in Büchereien Wien's own app, which we will also update soon after approval from the library.

**Comment by johan12345** [comment]
The new version of the Büchereien Wien app is now released: https://play.google.com/store/apps/details?id=de.opacapp.wien&hl=de

**Comment by berndy2001** [comment]
It now works again as usual, thank you very much.
I noticed two things:
The error message is transparent.
You are still asked for your date of birth.

![2019-07-03 23_04_54-Screenshot_20190703_225912_de opacapp wien](https://user-images.githubusercontent.com/1647619/60625235-75bf7a80-9de7-11e9-8dfc-e0e8381bc812.png)
![2019-07-03 23_07_09-Screenshot_20190703_225921_de opacapp wien](https://user-images.githubusercontent.com/1647619/60625236-76581100-9de7-11e9-8ad6-e6e98004082e.png)

**Comment by johan12345** [comment]
Thanks! We will address this in the next update.
