### ISSUE TITLE
Developers' Mailing List

### ISSUE THREAD

**Issue by StefRe** [opacapp/opacclient#569]
Is the mailing list (https://github.com/opacapp/opacclient/wiki/Mailing-list) still working? When I try to subscribe I get the following error `550 5.1.1 <dev-subscribe@opacapp.de>: Recipient address rejected: User unknown in virtual mailbox table `.

**Comment by raphaelm** [comment]
No, the mailing list does not exist for some 5+ years. I deleted the wiki page ;)
