### ISSUE TITLE
Stadtbücherei Hilden is broken

### ISSUE THREAD

**Issue by tobiasschueler** [opacapp/opacclient#579]
Some time ago the "Stadtbibliothek Hilden" did not work anymore. Error means "Connection to server failed...". I checked the domain "http://www.bibnet.de/webopac" which is configured in the app, is still valid. 

Any clue why this is happen?

**Comment by johan12345** [comment]
I'm sorry, this was probably due to a misconfiguration on our side, which should be fixed with https://github.com/opacapp/opacapp-config-files/commit/ab329c3cbd1582f21de1ff9092ce7100a811a129
You can load the new configuration using the corresponding button in the app settings.
