### ISSUE TITLE
F-Droid can't build - cwac-adapter no longer available

### ISSUE THREAD

**Issue by licaon-kter** [opacapp/opacclient#580]
https://github.com/commonsguy/cwac-adapter has moved?

**Comment by johan12345** [comment]
It seems that the cwac-adapter and cwac-endless are deprecated and the repositories have been made private. Similarly, e.g. cwac-pager will be deprecated as well in a few months: https://github.com/commonsguy/cwac-pager

In the long term, the solution is to migrate away from ListView to RecyclerView and use corresponding solutions for endless scrolling.

For a short term solution, would it be possible to use one of the forks of cwac-adapter and cwac-endless which are still around on GitHub for the F-Droid build?

**Comment by licaon-kter** [comment]
@johan12345 as you see fit... which ones? links?

**Comment by johan12345** [comment]
We have a fork of cwac-adapter at
https://github.com/opacapp/cwac-adapter

I thought we had one of cwac-endless as well, but we didn't, so I created one here:
https://github.com/opacapp/cwac-endless

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7009
