### ISSUE TITLE
New working "TH Nürnberg" json file

### ISSUE THREAD

**Issue by asdoi** [opacapp/opacclient#586]
New working json file:

`{"country":"Deutschland","_version_required":0,"data":{"baseurl":"https://opac.th-nuernberg.de/TouchPoint/","startparams":"Language=de&View=fhn&Branch=0"},"city":"Nürnberg","_plus_required":false,"account_supported":true,"_plus_store_url":null,"title":"Technische Hochschule","_notice_text":null,"geo":[49.452375,11.0925545],"_support_contract":false,"library_id":9119,"_active":true,"information":"https://www.th-nuernberg.de/einrichtungen-gesamt/zentrale-einrichtungen/bibliothek/","api":"touchpoint","state":"Bayern"}`

**Comment by johan12345** [comment]
Thanks! I have updated the configuration in our system, it should appear [here](https://github.com/opacapp/opacapp-config-files) soon and be updated in the app when you hit "update library data" in the settings.
