### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [opacapp/opacclient#609]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by raphaelm** [comment]
Feel free to go ahead and do it :)

**Comment by mondlicht-und-sterne** [comment]
The topic of PR and merge is too difficult for me.
You can, if you use Fastlane, just add screenshots
to make your app view more beautiful. So it was just
a hint that more can be displayed - if desired.

if you don't want to or can't, you can close the issue.
thanks anyway for reading.  :-)
