### ISSUE TITLE
Stadtbibliothek München - connection works, but media are missing

### ISSUE THREAD

**Issue by matthias6** [opacapp/opacclient#642]
Hi, I am using the German version. 
In the account information, 
There is no entry in "entliehen". 
Previously it worked, but now something is broken.

**Comment by raphaelm** [comment]
As per our support policy, we won't work on this, but someone from the community can for sure. However, it would probably need to be someone with an account in Munich to reproduce.

Support policy:
https://opac.app/de/support-policy/ / https://opac.app/en/support-policy/

**Comment by johan12345** [comment]
It might be that my PR #640 helps, because that library uses the same system. But it could also be a different error that is specific to Munich (where I have no account to test).

**Comment by raphaelm** [comment]
There's a slight chance c4d755e14d73b0ed458495fd96cf0b157f65651c will help, Zurich had the same issue
