### ISSUE TITLE
Bibliothek Würzburg changed provider to "Winbiap"

### ISSUE THREAD

**Issue by dueringa** [opacapp/opacclient#646]
The "Stadtbibliothek Würzburg" changed its OPAC provider around November/December to Winbiap.

Affected Versions of the app: 6.4.1 and earlier.

The library has no support contract, as far as I know, so I'll try to adapt the config files, test it on my device, and send a PR, if that's okay.

(The correct place for the PR will be https://github.com/opacapp/opacapp-config-files as far as I know, so I kinda misplaced the issue.)

**Comment by raphaelm** [comment]
Yeah, that would be great! :)
