### ISSUE TITLE
libopac: JCenter references and updates

### ISSUE THREAD

**Issue by tribut** [opacapp/opacclient#653]
[libopac's README](https://github.com/opacapp/opacclient/blob/master/opacclient/libopac/README.md) links to JCenter which has been offline since 2021. Is the library published somewhere else?

**Comment by raphaelm** [comment]
We don't publish it anywhere officially at the moment. It can be retrieved through jitpack, though: https://github.com/opacapp/libopac-sample-mvn/commit/5579b1d492f59ebb87623d4fa0facc0aa1f868f6

**Comment by tribut** [comment]
Thanks!
