### ISSUE TITLE
Stadtbibliothek Offenburg moved to Axiell

### ISSUE THREAD

**Issue by margin-auto** [opacapp/opacclient#655]
Stadtbibliothek Offenburg migrated its software to Arena software by Axiell (according to the url https://offenburg.arena.axiell.de/#/). So (the free version of) the app didn't work anymore for this library.
Since Axiell Arena is listed as compatible software (https://opac.app/de/compatibility/), is it possible to modify this in the app to reactivate the app for this library? Or are the needed modifications too much effort for the free version of the app?

**Comment by raphaelm** [comment]
Should be fixed already if you pull the new configuration data in settings
